# Generated by Django 5.1 on 2026-07-20 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('full_text', models.TextField(blank=True, default='')),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('extracted_fields', models.JSONField(blank=True, default=list)),
                ('suggested_category', models.CharField(blank=True, default='', max_length=200)),
                ('confidence_score', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'رزومه',
                'verbose_name_plural': 'رزومه\u200cها',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platforms', models.JSONField(default=list)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('level', models.CharField(choices=[('junior', 'جونیور'), ('mid', 'می\u200cلول'), ('senior', 'سنیور'), ('manager', 'مدیر'), ('all', 'همه سطوح')], default='all', max_length=20)),
                ('time_range', models.CharField(choices=[('1', '۱ روز گذشته'), ('3', '۳ روز گذشته'), ('7', '۷ روز گذشته'), ('14', '۱۴ روز گذشته'), ('30', '۳۰ روز گذشته'), ('all', 'همه')], default='7', max_length=10)),
                ('custom_keywords', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('total_results', models.IntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='core.resume')),
            ],
            options={
                'verbose_name': 'جستجو',
                'verbose_name_plural': 'جستجوها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('salary', models.CharField(blank=True, default='', max_length=200)),
                ('job_type', models.CharField(blank=True, default='', max_length=100)),
                ('seniority_level', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('url', models.URLField(blank=True, default='')),
                ('remote', models.BooleanField(default=False)),
                ('posted_date', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='core.jobsearch')),
            ],
            options={
                'verbose_name': 'آگهی استخدام',
                'verbose_name_plural': 'آگهی\u200cهای استخدام',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['search', 'platform'], name='core_joblis_search__3259a9_idx')],
            },
        ),
    ]
